[package]
name = "randomness"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff.workspace = true
sha3.workspace = true
poseidon = { path = "../poseidon" }
felt = { path = "../felt" }

[dev-dependencies]
lazy_static = "1.5.0"
