[package]
name = "poseidon"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
ark-ff.workspace = true
felt = { path = "../felt" }
hex.workspace = true

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "poseidon"
harness = false
