[package]
name = "fft"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff.workspace = true
ark-poly.workspace = true
felt = { path = "../felt" }
randomness = { path = "../randomness" }
channel = { path = "../channel" }
sha3.workspace = true
hex-literal.workspace = true
